### ISSUE TITLE
Week 2 Reference Files : Box

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team2#1]
- Overview of Hills
- Week 2 Assignments

[]https://app.box.com/s/0d56tulvikzilbzixgfc1fg2h3c963yn

**Comment by akallish** [comment]
@SanhyongPark @k8forz @walkoutthebox please move this task to the product backlog pipeline and when ready to initiate the task, please move it to the in progress pipeline. Remember that all asynchronous task conversations need to happen in the GitHub tasks found in the issues tab. To reference people, use their GitHub handle. If you need help reference @akallish and I will get a notification. Thanks.

**Comment by SanhyongPark** [comment]
Done.
