### ISSUE TITLE
Week 03 : In GitHub : Transfer stories to GitHub

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team2#11]
- create two new tags : “story” and specific “(epic name)” tags
- create a new issues and give a story a name assign the team to the story
- select appropriate tags for story choose week three milestone state what part of the hill and what part of the sub-hill it is decomposed from
- draft the first iteration of the hill statement other team members then iterate and then @ reference others on the team  just like the hills/definitions/sub hills exercise, it is important to refine the language of the story

**Comment by k8forz** [comment]
Can someone else take ownership of adding the stories to the product backlog? I am, unexpectedly, taking on another TA position today and could use some help on getting this Issue #11 done

Alternatively, maybe we each can do 5?

**Comment by arijit1035** [comment]
@k8forz I am on it.
