### ISSUE TITLE
Week 2 Homework : Read Online Articles

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team2#2]
- IBM Hills Overview : []https://ibm.co/2AfH2yA)
- Agile Terminology : []http://bit.ly/2uwt8Va

**Comment by akallish** [comment]
@SanhyongPark @k8forz @walkoutthebox please move this task to the product backlog pipeline and when ready to initiate the task, please move it to the in progress pipeline. Remember that all asynchronous task conversations need to happen in the GitHub tasks found in the issues tab. To reference people, use their GitHub handle. If you need help reference @akallish and I will get a notification. Thanks.

**Comment by k8forz** [comment]
So FYI team @arijit1035 @SanhyongPark @walkoutthebox these readings are the 1st step...I'm starting to realize so I thought I'd ping y'all to start here!

**Comment by arijit1035** [comment]
Its done from my side.

**Comment by k8forz** [comment]
Great!

**Comment by SanhyongPark** [comment]
Done.

**Comment by akallish** [comment]
> So FYI team @arijit1035 @SanhyongPark @walkoutthebox these readings are the 1st step...I'm starting to realize so I thought I'd ping y'all to start here!

The review materials are always the first order of business before the team does it’s tasks.
