### ISSUE TITLE
Week 4 : Continue to refine stories

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team2#35]
Teams should continue to iterate, refine, consolidate and close stories to tighten up their overall backlog of work. 

- [x] Kait Silva Forsythe
- [ ] Julian Walker
- [x] Sanhyong Park
- [x] Arijit Patra

**Comment by k8forz** [comment]
@akallish Is this an ongoing task? I believe we completed our review and editing the story tasks  based on your comments/suggestions. Would this mean we are done refining and can move this task to done?

**Comment by akallish** [comment]
@k8forz if the team and @arijit1035 feels that all the stories are refined, then this task can be moved to done, or closed.
