### ISSUE TITLE
Week 4 : Written Content

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team2#36]
[Chris Profile] (https://bit.ly/3pKhi55)
[CDK Website] (http://bit.ly/3taEF9M)
[SAFe Overview] (http://bit.ly/2MHxGnX)

- [x] Kait Silva Forsythe
- [ ] Julian Walker
- [x] Sanhyong Park
- [x] Arijit Patra

**Comment by k8forz** [comment]
Hey @akallish just an FYI the link in the Box slides for "CDK Global" goes to this address - [https://madeintandem.com/blog/goruco-2017-trust-teams/]
Thanks for including it here as well though!
