### ISSUE TITLE
Week 2 Homework : GitHub

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team2#4]
Explore your GitHub repository. Go into each individual homework task and ask questions, have conversations in the task comment areas. Remember use "@" to refer to your team mates or you can put me in the stream by referring to my handle @akallish

Team 2 : IITIDIDX597/sp_2021_team2 : []https://bit.ly/39BvWV4

**Comment by SanhyongPark** [comment]
Does this work?

**Comment by SanhyongPark** [comment]
Wow, it works! Cool.

**Comment by k8forz** [comment]
Great! I will get on this task. Still trying to learn this platform eek!

**Comment by akallish** [comment]
@SanhyongPark @arijit1035 @walkoutthebox @k8forz For next week, I will be going into the greater details of GitHub to support week 3 activities. Even then we will probably only be using 2% of the platforms potential!

**Comment by SanhyongPark** [comment]
Sounds good! Looking forward to exploring more features of Github.
