### ISSUE TITLE
Week 5 Out of Class Work : Watch Online Videos

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team2#49]
- [x] Kait Silva Forsythe
- [x] Julian Walker
- [x] Sanhyong Park
- [x] Arijit Patra

Review these videos BEFORE writing acceptance criteria

[Story to Acceptance Criteria] (http://bit.ly/2E7JqGq)

**Comment by k8forz** [comment]
I also recommend this video: https://www.youtube.com/watch?v=OWG0KE5GZJY

**Comment by akallish** [comment]
@k8forz Thanks for the link to this video. The narrator sounds like a bot but the video covers all the tight information
