### ISSUE TITLE
Week 5 Out of Class Work : Create acceptance criteria for five stories

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team2#50]
- [x] Kait Silva Forsythe
- [x] Julian Walker
- [x] Sanhyong Park
- [x] Arijit Patra

- THREE ITERATIONS of acceptance criteria for each story is required.
- Tag the five stories as "Acceptance Criteria"

**Comment by arijit1035** [comment]
@k8forz @SanhyongPark @walkoutthebox 

Suggested acceptance criteria format 1: 
Given that <role> 
When <do a task> 
Then <action from the product/system>

Suggested acceptance criteria format 2:
A <role>
should <see/be able to do>
the following <task1, 2, 3...> 
Edge case:
<Things don't work/getting out of problems Case 1,2,3....>

**Comment by akallish** [comment]
@arijit1035 first the team should discuss which five stories (use story numbers). Then write the acceptance criteria in those existing stories.

**Comment by arijit1035** [comment]
@akallish We will be doing the same Adam, we just had our meeting and I included this text as my understanding of how it is written from the readings and videos.

**Comment by akallish** [comment]
@arijit1035 great. I am not art directing, just having a conversation

**Comment by k8forz** [comment]
Hey team @arijit1035 @SanhyongPark @walkoutthebox - anybody feel strongly any specific epics we can create acceptance criteria for?

**Comment by arijit1035** [comment]
@k8forz @SanhyongPark @walkoutthebox I think the points where cabi directly helps the users are the epics 'guidance/smart assistance' 'maintaning inventory' and 'dieting & nutrition'. These 3 are in descending order of primary functions for me.

**Comment by SanhyongPark** [comment]
@k8forz @SanhyongPark @walkoutthebox Totally agree. 'Guidance/smart assistance' can be our focus.
