### ISSUE TITLE
Week 03 : Review Online Written Content

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team2#8]
Please read these articles in their entirety - before doing the tasks

What are user stories? 
(http://bit.ly/2Gmw7Y6 )
(http://bit.ly/2IQVdwl )
(http://bit.ly/2pDhEgx)

GitHub Issues 
(http://bit.ly/2rjMACX)

Creating tasks in issues 
(http://bit.ly/2HSHGGG)

Text Formatting 
(http://bit.ly/2YceDov)

**Comment by SanhyongPark** [comment]
Done
