### ISSUE TITLE
Week 03 : Review Videos

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/sp_2021_team2#9]
Please watch these videos in their entirety - before doing the tasks 

GitHub Overviews
 (http://bit.ly/2Gedxhz)
 (http://bit.ly/2G8muwR)

GitHub & ZenHub 
(https://bit.ly/3qWfLZT)

How to write user stories
 (http://bit.ly/2IMDQwJ) 
(http://bit.ly/2I1gZMM)

**Comment by k8forz** [comment]
Done. I will post my notes in Slack and Mural

**Comment by SanhyongPark** [comment]
Done
